# Generated by Django 2.2.5 on 2019-10-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('becomeamodel', '0002_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
